name: Release Binary

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: Release Binary
    runs-on: macos-12
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: brew install coreutils

      - name: Build
        run: make package-darwin_arm64

      - name: Attach Binaries to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
          files: |
            bin/batt-packages-latest/*
